### ISSUE TITLE
README could specify the naming convention required for CUH/NUH

### ISSUE THREAD

**Issue by RSWilson1** [eastgenomics/variant_workbook_parser#10]
https://github.com/eastgenomics/variant_workbook_parser/blob/17eb12ea9d3846921f8a86769f1ec329fe99a369/variant_workbook_parser.py#L194C1-L211C20

**Comment by kjwinfield** [comment]
@RSWilson1 these are specified in the config here: https://github.com/eastgenomics/variant_workbook_parser/blob/17eb12ea9d3846921f8a86769f1ec329fe99a369/parser_config.json#L12C1-L13C21

Is that enough? / Where would you want them specified in the readme if not?

**Comment by RSWilson1** [comment]
Maybe just a small section for highlighting the config is used. Here's a rough draft.

### Configuration file (`parser_config.json`)
This sets the variables required for recording submission information for ClinVar.
It also sets the folders for gathering workbooks and the DNAnexus project for uploading the CSVs.

#### Example Config format:
```
{
"config_information":{
"config_version": "1.1.0"
},
"info":{
"CUH Organisation": "Cambridge Genomics Laboratory",
"NUH Organisation": "Genomics and Molecular Medicine Service",
"Institution": "East Genomic Laboratory Hub, NHS Genomic Medicine Service",
"Collection method": "clinical testing",
"Allele origin": "germline",
"Affected status": "yes",
"CUH folder": "CUH",
"NUH folder": "NUH",
"CUH org ID": 111111,
"NUH org ID": 111111,
"csv_projectID": "project-xxxx"
}
}
```
